sudo: required
services:
  - docker

before_install:
  - docker build -t kovacics/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kovacics/docker-react npm run test

deploy:
  provider: heroku
  app: docker-react-kovacics
  api_key: $API_KEY
